### ISSUE TITLE
Error Mediatek MTK8321

### ISSUE THREAD

**Issue by igorwhite** [NanoBytesInc/miners#3]
Hello!
Many thanks for the work done!

Tablet: 
Processor: Mediatek MTK8321 ARMv7 32-bit
System: Android 5.1

I get an error: 
WARNING: linker: ./xmrig unused DT entry: type 0x6ffffffe arg 0x92b8 
WARNING: linker: ./xmrig unused DT entry: type 0x6ffffff arg 0x2 
Bus error 
I helped this here: https://github.com/kost/android-elf-cleaner 
Errors: entry: type 0x6ffffffe arg 0x92b8 and type 0x6ffffff arg 0x2 - disappeared
Remained error: Bus error
What could be the problem?

**Comment by igorwhite** [comment]
I updated the firmware of the tablet and all the errors were gone.
All many thanks!

**Comment by NanoBytesInc** [comment]
Awesome!
